services:
  # Mongo replica set config source: https://github.com/prisma/prisma/tree/main/docker
  mongo:
    build:
      context: ./mongodb_replica
      args:
        MONGO_VERSION: latest
    environment:
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27017
      MONGO_COMMAND: "mongosh"
    ports:
      - "27017:27017"
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "admin",
          "--port",
          "27017",
          "--eval",
          "db.adminCommand('ping').ok",
        ]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - devthreads-db:/data/db
volumes:
  devthreads-db:
